<?php

define("_RATINGS","Kundenbewertungen");
define("_RATINGSNOVALUATIONS","Aktuell sind noch keine Bewertungen vorhanden!");
define("_RATINGSVENDORSTATS","Shop-Statistik:");
define("_RATINGSVALUATIONS","Bewertungen");
define("_RATINGSCONCILIATIONSOK","erfolgreiche Schlichtungsverfahren");
define("_RATINGSCONCILIATIONSNO","erfolglose Schlichtungsverfahren");
define("_RATINGSCONCILIATIONOK","Das Schlichtungsverfahren war erfolgreich!");
define("_RATINGSCONCILIATIONNO","Das Schlichtungsverfahren blieb erfolglos!");
define("_RATINGSCUSTOMEROPINIONS","Kundenmeinungen");
define("_RATINGSVALUATIONSFROMCTOC","Bewertungen von Kunden für Kunden");
define("_RATINGSREPORTED","Diese Bewertung wird gerade geprüft um eine Lösung zu finden.");
define("_RATINGSANSWERFROM","Antwort von");
define("_RATINGSNEXTSITE","nächste Seite");
define("_RATINGSPREVIOUSSITE","vorherige Seite");
define("_RATINGSCURRENTVALUATION","Aktuelle Bewertung");
define("_RATINGSADDRESS","Anschrift:");
define("_RATINGSHOLDER","Berechtigter:");
define("_RATINGSEMAIL","Email:");
define("_RATINGSPHONE","Telefon:");
define("_RATINGSFAX","Fax:");
define("_RATINGSPOSITIVE","positiv");
define("_RATINGSNEUTRAL","neutral");
define("_RATINGSNEGATIVE","negativ");
define("_RATINGSWEGARANTEE","Wir garantieren");
define("_RATINGSGARANTEEINFO","Es werden von uns zu keiner Zeit Bewertungen gelöscht, ausser es handelt sich dabei nachweislich um unrechtmässige Bewertungen z.B.,wenn der Kunde seine Leistungen nicht bezahlt oder vorab von seinem Widerrufsrecht gebrauch gemacht hat.<br><br>Schlechte Bewertungen, welche im Schlichtungsverfahren zur vollen Zufriedenheit des Kunde geklärt werden konnten bleiben erhalten, werden jedoch nicht gewertet.<br><br>Wie das Bewertungssystem genau funktioniert und welche Sicherheiten es für Sie als Kunde bietet können Sie unter folgendem Link lesen.");
define("_RATINGSNOTYET","Fehler - Keine Bewertung möglich");
define("_RATINGSNOTYETINFO","Sie sind leider nicht berechtigt den Shopbetreiber zu bewerten. Falls Sie eine Email erhalten haben, mit der Bitte Ihren Anbieter zu bewerten, so rufen Sie den Link aus der Email noch einmal auf. Sollten Sie dann immer noch diesen Fehler hier sehen, senden Sie uns bitte Ihren Link an service@teklab.de. Wir werden dies dann umgehend kontrollieren.");
define("_RATINGSBACK","Zurück");
define("_RATINGSNORATING","Sie haben keine Bewertung vorgenommen. Bitte gehen Sie zurück und bewerten Sie den Shopbetreiber.");
define("_RATINGSNOCOMMENT","Sie haben keinen Kommentar geschrieben. Bitte gehen Sie zurück und schreiben Sie einen Kommentar.");
define("_RATINGSTOSHORT","Der Kommentar ist zu kurz. Bitte gehen Sie zurück und schreiben Sie einen ausführlicheren Kommentar.");
define("_RATINGSALREADYRATED","Es wurde bereits eine Bewertung abgegeben. Sie können Ihre Bewertung nicht mehr ändern.");
define("_RATINGSDBERROR","Ihre Bewertung konnte nicht gespeichert werden. Versuchen Sie es bitte erneut.");
define("_RATINGSDBSAVED","Danke, dass Sie sich die Zeit genommen haben den Shopbetreiber zu bewerten. Sie können das Browserfenster jetzt schliessen");
define("_RATINGSTOP","Top");
define("_RATINGSFLOP","Flop");
define("_RATINGSTEPONE","1. Schritt - Status");
define("_RATINGSTEPTWO","2. Schritt - Bewerten");
define("_RATINGSTEPTHREE","3. Schritt - Kommentieren");
define("_RATINGSTEPFOUR","4. Schritt - Kontrollieren");
define("_RATINGSTEPFIVE","5. Schritt - Abschicken");
define("_RATINGSTEPONEINFOMEM","Sie sind als User {%customerid%} angemeldet. Wollen Sie die Bewertung für andere User anonym abgeben, so loggen Sie sich bitte zuerst aus. (<a href=\"members.php?op=Logout\" target=\"_blank\">ausloggen</a>)");
define("_RATINGSTEPONEINFONOMEM","Sie sind derzeit nicht angemeldet oder haben noch keinen Kundenaccount. Daher wird die Bewertung anonym abgegeben. Wenn Sie jedoch Ihren Shopbetreiber unterstützen wollen, dann melden Sie sich bitte vorher im Kundenbereich an.");
define("_RATINGSTEPTWOINFO","Vergeben Sie bitte Ihre Bewertung. Wählen Sie dazu das zutreffende Auswahlfelder aus.");
define("_RATINGSTEPTHREEINFO","Vermeiden Sie bitte übermäßigen Gebrauch von Beleidigungen und Schimpfwörtern, da solche Bewertungen entfernt werden könnten. Bleiben Sie bitte immer sachlich und fair.");
define("_RATINGSTEPFOURINFO","Bitte kontrollieren Sie noch einmal Ihre Bewertung, denn eine Bearbeitung ist später nicht mehr möglich. Haben Sie den Anbieter richtig bewertet? Sind Sie der Meinung, dass Ihr Kommentar so bleiben soll?");
define("_RATINGSTEPFIVEINFO","Klicken Sie jetzt auf den Button \"Bewertung veröffentlichen\", wenn Sie die Bewertung so abgeben wollen.");
define("_RATINGSSENDBUTTON","Bewertung veröffentlichen");
define("_RATINGSNOTCONFIRMED","Fehler - Keine Bestätigung der Schlichtung möglich");
define("_RATINGSNOTCONFIRMEDINFO","Sie sind leider nicht berechtigt die erfolgreiche Schlichtung zu bestätigen. Falls Sie eine Email erhalten haben, mit der Bitte, eine Schlichtung des offenen Falls zu bestätigen,so rufen Sie den Link aus der Email noch einmal auf. Sollten Sie dann immer noch diesen Fehler hier sehen, setzen Sie sich mit Ihrem Shopbetreiber in Verbindung.");
define("_RATINGSCONFIRMED","Schlichtung erfolgreich");
define("_RATINGSCONFIRMEDINFO","Wir bedanken uns, dass Sie sich die Zeit genommen haben, die erfolgreiche Schlichtung des Falles zu bestätigen.");
define("_RATINGSCOUNT","Stimmen");

?>